apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    pod-name: pod1
spec:
  containers:
  - name: pod1
    image: quay.io/markdgray/centos:latest
    command:
      - /sbin/init
  nodeName: master-0.ostest.test.metalkube.org
