apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    pod-name: pod1
spec:
  containers:
  - name: pod2
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
  nodeName: ip-10-0-241-12.us-west-1.compute.internal

