apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    pod-name: pod2
spec:
  containers:
  - name: pod2
    image: quay.io/markdgray/centos:latest
    command:
      - /sbin/init
  nodeName: master-1.ostest.test.metalkube.org
