apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    pod-name: pod2
spec:
  containers:
  - name: pod2
    image: docker.io/centos/tools:latest
    command:
      - /sbin/init
  nodeName: ip-10-0-157-28.us-west-1.compute.internal 
