---

- name: Configure IPsec (self-signed)
  hosts: n77 n91
  vars:
    target_dir: /root/
    tunnel_type: gre
    branch: master 
  tasks:
  - import_tasks: ovs.yml
  - name: Configure OVS IPsec (Private Key)
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: private_key
      value: absent
      state: absent
  - name: Configure OVS IPsec (Certificate)
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: certificate
      value: absent
      state: absent
  - name: Configure OVS IPsec (CA Certificate)
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: ca_cert
      value: absent
      state: absent

  - name: Remove Tunnel Ports
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: absent
        
  - name: Setup Tunnel Ports
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: present
      set: "Interface tun type={{ tunnel_type }}  options:remote_ip={{ hostvars[remote_name]['ansible_default_ipv4']['address'] }} options:psk=swordfish"
        
