---

- name: Configure IPsec (CA-signed)
  hosts: n77 n91
  vars:
    tunnel_type: gre
    target_dir: /tmp
  tasks:
  - name: Add br-ipsec
    become: true
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: br-ipsec
      state: present
  # Is there a better way to setup networking
  - name: Set up bridge IP address
    become: true
    shell: |
      ip --force addr add {{ local_ip }}/24 dev br-ipsec
      ip --force link set br-ipsec up

  - name: Create test directory
    file:
      path: "{{ target_dir }}/test/"
      state: directory

  - name: Generate cert
    become: true
    command:
      cmd: ovs-pki req --force -u {{ item }}
      chdir: "{{ target_dir }}/test"
    delegate_to: "{{ ansible_play_hosts_all.0 }}"
    loop: "{{ ansible_play_hosts_all }}"
    run_once: true

  - name: Create CA
    become: true
    command:
      cmd: ovs-pki init --force
      creates: /var/lib/openvswitch/pki
    delegate_to: "{{ ansible_play_hosts_all.0 }}"
    run_once: true

  - name: Sign all certs
    become: true
    command:
      cmd: ovs-pki sign --force -b {{ item }} switch
      chdir: "{{ target_dir }}/test"
    delegate_to: "{{ ansible_play_hosts_all.0 }}"
    loop: "{{ ansible_play_hosts_all }}"
    run_once: true

  - name: Synchronize all signed certs
    become: true
    synchronize:
      src: "{{ target_dir }}/test/"
      dest: "{{ target_dir }}/test/"
      rsync_opts: "--rsh=/usr/bin/ssh -S none -i ~/.ssh/id_rsa -o Port=22 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
      private_key: "~/.ssh/id_rsa"
      dirs: yes
    delegate_to: "{{ ansible_play_hosts_all.0 }}"

  - name: Copy CA certs
    become: true
    synchronize:
      src: /var/lib/openvswitch/pki/switchca/cacert.pem
      dest: "{{ target_dir }}/test/"
    delegate_to: "{{ ansible_play_hosts_all.0 }}"

  - name: Configure OVS IPsec (Private Key)
    become: true
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: private_key
      value: "{{ target_dir }}/test/{{ inventory_hostname }}-privkey.pem"
  - name: Configure OVS IPsec (Certificate)
    become: true
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: certificate
      value: "{{ target_dir }}/test/{{ inventory_hostname }}-cert.pem"
  - name: Configure OVS IPsec (CA Certificate)
    become: true
    openvswitch.openvswitch.openvswitch_db:
      table: Open_vSwitch
      record: .
      col: other_config
      key: ca_cert
      value: "{{ target_dir }}/test/cacert.pem"

  - name: Remove Tunnel Ports
    become: true
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: absent

  - name: Setup Tunnel Ports
    become: true
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: present
      set: Interface tun type={{ tunnel_type }}  options:remote_ip={{ hostvars[remote_name]['ansible_default_ipv4']['address'] }} options:remote_name={{ remote_name }}

