---

- name: Configure IPsec (PSK)
  hosts: n77 n91
  vars:
    tunnel_type: gre
  tasks:
  - name: Add br-ipsec
    become: true
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: br-ipsec
      state: present
  # Is there a better way to setup networking
  - name: Set up bridge IP address
    become: true
    shell: |
      ip --force addr add {{ local_ip }}/24 dev br-ipsec
      ip --force link set br-ipsec up
  - name: Remove Tunnel Ports
    become: true
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: absent

  - name: Setup Tunnel Ports
    become: true
    openvswitch.openvswitch.openvswitch_port:
      bridge: br-ipsec
      port: tun
      state: present
      set: "Interface tun type={{ tunnel_type }}  options:remote_ip={{ hostvars[remote_name]['ansible_default_ipv4']['address'] }} options:psk=swordfish"

