---
- name: Install OVS IPsec from source
  hosts: n77

  tasks:

  - name: Get dependencies
    become: true
    yum:
      name:
        - gcc
        - libtool
        - autoconf
        - automake
        - make
      state: present
  - name: Remove openvswitch package
    become: true
    yum:
      name:
        - openvswitch
        - openvswitch-ipsec
      state: absent

  - name: Clone OVS
    git:
      repo: 'https://github.com/openvswitch/ovs.git' 
      dest: ~/test/ovs

  - name: Configure OVS build
    shell: |
      pushd ~/test/ovs
      ./boot.sh
      ./configure
    args:
      creates: ~/test/ovs/Makefile
  
  - name: Build OVS
    make:
      chdir: ~/test/ovs

  - name: Install OVS
    become: true
    make:
      chdir: ~/test/ovs
      target: install

  - name: Start OVS
    command:
      cmd: ovs-ctl start
      creates: 

  - name: Test
    openvswitch.openvswitch.openvswitch_bridge:
      bridge: mark
      state: present
        
