---

- name: Install OVS from Git
  hosts: n77 n91
  vars:
    target_dir: /root/
    branch: master
  become: true
  tasks:
  - name: Get dependencies
    yum:
      name:
        - git
        - gcc
        - libtool
        - autoconf
        - automake
        - make
        - libreswan
        - libcap-ng-devel
        - openssl-devel
        - python36
      state: present
  - name: Remove openvswitch package
    yum:
      name:
        - openvswitch
        - openvswitch-ipsec
        - python3-openvswitch
      state: absent

    # Do this before starting OVS because of https://bugzilla.redhat.com/show_bug.cgi?id=1814154
  - name: Stop firewalld
    service:
      name: firewalld
      state: stopped

  - name: Clone OVS
    git:
      repo: 'https://github.com/markdgray/ovs.git'
      dest: "{{ target_dir }}/ovs"
      version: "{{ branch }}"
      update: yes

  - name: Configure OVS build
    shell: |
      ./boot.sh
      ./configure
    args:
      creates: "{{ target_dir }}/ovs/config.h"
      chdir: "{{ target_dir }}/ovs"

  - name: Build OVS
    make:
      chdir: "{{ target_dir }}/ovs"

  - name: Install OVS
    make:
      chdir: "{{ target_dir }}/ovs"
      target: install

  - name: Stop OVS IPsec
    command:
      cmd: /usr/local/share/openvswitch/scripts/ovs-ctl stop-ovs-ipsec
    environment:
      OVS_RUNDIR: /usr/local/var/run/openvswitch/

  - name: Stop OVS
    command:
      cmd: /usr/local/share/openvswitch/scripts/ovs-ctl stop
    environment:
      OVS_RUNDIR: /usr/local/var/run/openvswitch/

  - name: Clear OVS database
    file:
      path: /usr/local/etc/openvswitch/conf.db
      state: absent

  - name: Start OVS
    command:
      cmd: /usr/local/share/openvswitch/scripts/ovs-ctl start
    environment:
      OVS_RUNDIR: /usr/local/var/run/openvswitch/

  - name: Start OVS IPsec
    command:
      cmd: /usr/local/share/openvswitch/scripts/ovs-ctl --ike-daemon=libreswan start-ovs-ipsec
    environment:
      PYTHONPATH: /usr/local/share/openvswitch/python/
      OVS_RUNDIR: /usr/local/var/run/openvswitch/

  - name: Start service ipsec, if started
    service:
      name: ipsec
      state: started
