- name: Get dependencies
  become: true
  yum:
    name:
      - gcc
      - libtool
      - autoconf
      - automake
      - make
      - libreswan
      - libcap-ng-devel
    state: present
- name: Remove openvswitch package
  become: true
  yum:
    name:
      - openvswitch
      - openvswitch-ipsec
    state: absent

- name: Clone OVS
  git:
    repo: 'https://github.com/markdgray/ovs.git' 
    dest: "{{ target_dir }}/test/ovs"
    version: "{{ branch }}"
    update: yes

- name: Configure OVS build
  shell: |
    ./boot.sh
    ./configure
  args:
    creates: "{{ target_dir }}/test/ovs/config.h"
    chdir: "{{ target_dir }}/test/ovs"

- name: Build OVS
  make:
    chdir: "{{ target_dir }}/test/ovs"

- name: Install OVS
  become: true
  make:
    chdir: "{{ target_dir }}/test/ovs"
    target: install

- name: Stop OVS IPsec
  command:
    cmd: /usr/local/share/openvswitch/scripts/ovs-ctl stop-ovs-ipsec
  environment:
    OVS_RUNDIR: /usr/local/var/run/openvswitch/

- name: Stop OVS
  command:
    cmd: /usr/local/share/openvswitch/scripts/ovs-ctl stop
  environment:
    OVS_RUNDIR: /usr/local/var/run/openvswitch/

- name: Start OVS
  command:
    cmd: /usr/local/share/openvswitch/scripts/ovs-ctl start
  environment:
    OVS_RUNDIR: /usr/local/var/run/openvswitch/

- name: Start OVS IPsec
  command:
    cmd: /usr/local/share/openvswitch/scripts/ovs-ctl --ike-daemon=libreswan start-ovs-ipsec
  environment:
    PYTHONPATH: /usr/local/share/openvswitch/python/
    OVS_RUNDIR: /usr/local/var/run/openvswitch/

- openvswitch.openvswitch.openvswitch_bridge:
    bridge: br-ipsec
    state: present

- name: Stop service httpd, if started
  service:
    name: ipsec
    state: started

# Is there a better way to setup networking
- name: Set up bridge IP address
  shell: |
    ip --force addr add {{ local_ip }}/24 dev br-ipsec
    ip --force link set br-ipsec up
